---
title: "Basic functions"
output:
  html_document:
    df_print: paged
---

Get similarity score, with a record of operations taken (simple example):

```{r, message=F}
library(segsimflex)

data_raw = c("JOHN: Hello , how are you ? MARY: I am fine , thank you .", "JOHN: Hello how are you ? MARY: I am fine thank you .")
data_df = create_dfs(data_raw)
segsimflex::sim_Score(data_df[[1]], data_df[[2]], boundaries = c(",", "?", "."), record = T)
```


Get similarity score:
```{r, message=F}
M_nccu = matrix(
  c(1, .5, .25, .25, 1, 0,
    .5, 1, .5, .5, 1, .25,
    .25, .5, 1, .25, 1, 0,
    .25, .5, .25, 1, 1, .25,
    1,1,1,1,1, 1,
    0, .25, 0, .25, 1, 1),
  nrow = 6)
bounds_nccu = c(",", ".", "?", "--")
transCost = (1-M_nccu[,6])*.5
nccu_t001 = nccu_squareno[[1]]
t01_sim = segsimflex::sim_Score(nccu_t001[[1]], nccu_t001[[2]], transCost = transCost, m = M_nccu, boundaries = bounds_nccu)
t01_sim
```

Get IAA (K = 2 for speed, for display purposes):
```{r, message=F}
t01_iaa_m = segsimflex::IAA(nccu_t001[[1]], nccu_t001[[2]], transCost = transCost, m = M_nccu, boundaries = bounds_nccu, K = 2)
t01_iaa_m
```
